### ISSUE TITLE
Copy value to clipboard buttons should copy the data field contents not the field label

### ISSUE THREAD

**Issue by popocrat** [CityOfDetroit/base-unit-tools#41]
Please change the contents copied by the Button with tooltip "Copy value to clipboard" from the field name e.g. Taxpayer, to the contents of the Taxpayer field. I think this is the case for all the Copy Buttons. 
![BU Tools Copy Button](https://github.com/CityOfDetroit/base-unit-tools/assets/2375855/2775aa6b-05dc-4c0c-bb82-b8c35df5d3c7)

**Comment by jmcbroom** [comment]
dang, that's embarrassing. for me

**Comment by jmcbroom** [comment]
Should be fixed!

**Comment by popocrat** [comment]
Much appreciated! I <3 copy/paste
