### ISSUE TITLE
Show all the available Detroit Street View images within the Base Units Map

### ISSUE THREAD

**Issue by alicehargreaves** [CityOfDetroit/base-unit-tools#45]
Issue originally created by @jmcbroom on Feb 10, 2023.

Mapillary changed its API to retrieve Detroit Street View images and show them within the Base Units map. We should refactor our approach to pulling this imagery.

If the API route doesn't work, we should figure out a different solution by working with the Enterprise GIS team directly on this.

**Comment by alicehargreaves** [comment]
Ted Schultz inquired about the status of this issue on 9/17/2024, since he was asked by DPW staff using the base units tool if the street view program was still running.

We discussed a stopgap measure to add text that says "Click here for more recent street view imagery" and provide a link to the current lat long of the state of the map. ie https://www.mapillary.com/app/?lat=42.4020286&lng=-82.9325148&z=19.9&username%5B%5D=codgis.

There are two future options for this that EGIS is exploring:
1. Oriented imagery on-prem with privacy blurring we could host our own imagery and make it public
2. ESRI development team is working with Mapillary and Meta to publish their own catalogue

**Comment by jmcbroom** [comment]
well im sorry to report that it was some silly code on my part that obscured these -- i arbitrarily set a cutoff in the code that prevented recent imagery from showing up. my bad. 

<img width="387" alt="Screenshot 2024-09-20 at 8 55 08 AM" src="https://github.com/user-attachments/assets/60f48afa-f25b-403b-b670-107762a4bcec">

it's fixable but will take me some time to find the correct balance here

**Comment by jmcbroom** [comment]
feeling a bit less silly -- it turns out our "organization_id" changed at some point, and we were filtering down based on that.
