### ISSUE TITLE
Map should use our Street Names as labels instead of the street names from ESRI

### ISSUE THREAD

**Issue by alicehargreaves** [CityOfDetroit/base-unit-tools#47]
@jmcbroom created this issue on April 16th, 2021

Folks have pointed out some weird street names on the ESRI labels (ie an alleyway named Woodward), so let's replace the labels with one generated from our streets and street names.

**Comment by jmcbroom** [comment]
Closing since we are using Ted's labels -- eventually we should get around to updating that but technically I think we've fulfilled this issue.
